// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbwPf9j8_idWWVLC2Qt-1zAGaKfxaZeehO9cKJBgDLuA6JWzb0J3Fx8DjiphlzUPJQSWQQ/exec";
